name: brewandq
favicon: null
layout_spectrum: 0.7612039390951395
typography_spectrum: 0.41505803912878036
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.4998585651628673
  lightness: 0.8274957232642919
  saturation: 0.7568892729468644
  rhythmicContrast: 0.730279078707099
purpose: []
